"""Remove friendship_token_label column

Revision ID: 8f43cf5d5cd9
Revises: 
Create Date: 2025-11-09 20:29:59.612792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f43cf5d5cd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_requests', 'friendship_token_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_requests', sa.Column('friendship_token_label', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
