"""add_source_type_to_print_requests

Revision ID: ff8f06aa9902
Revises: 8f43cf5d5cd9
Create Date: 2025-11-22 00:00:11.587239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8f06aa9902'
down_revision: Union[str, Sequence[str], None] = '8f43cf5d5cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we can add the column with a default value directly
    # This will apply 'user' to all existing rows
    op.add_column('print_requests', sa.Column('source_type', sa.String(length=20), nullable=False, server_default='user'))
    op.create_index(op.f('ix_print_requests_source_type'), 'print_requests', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_requests_source_type'), table_name='print_requests')
    op.drop_column('print_requests', 'source_type')
    # ### end Alembic commands ###
